version: '3.7'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.60.0/24

volumes:
  cs-ansible:

services:
  cicd:
    image: agupta73/cicd
    ports:
       - "8011:80"
    networks:
      custom:
        ipv4_address: 192.168.60.11
    dns: 8.8.8.8
    container_name: uicicd1
    hostname: cicd
    restart: always
    
  cicd2:
    image: agupta73/cicd
    ports:
       - "8012:80"
    networks:
      custom:
        ipv4_address: 192.168.60.12
    dns: 8.8.8.8
    container_name: uicicd2
    hostname: cicd
    restart: always
    
  cicd_db:
    image: agupta73/dbcicd
    ports:
      - "3305:3306"
    networks:
      custom:
        ipv4_address: 192.168.60.13
    dns: 8.8.8.8
    container_name: dbcicd
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: kdms
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
       - type: bind
         source: ../CICD_DB/CICD_Conf/my.cnf
         target: /etc/my.cnf
       - type: bind
         source: ../CICD_DB/CICD_Data
         target: /var/lib/mysql
    restart: always

